SAP/techne

src/less/globals/_variables.less

Please check if its the right color. At least the variable exist and less file renders again for me.

less not rendering to css. changed variable. Is this the right color?

---

src/less/overwrites/_buttons.less
src/less/overwrites/_listgroup.less
src/less/overwrites/_navs.less
src/less/overwrites/_panels.less

Lets see if this helps with some questions we had about deprecated components.

deleted misleading deprecation informations

---

LICENSE

Updated licence

---

bower.json
package.json

License update to Apache 2.0
Definitions updated
Mobile table display updated for consistency
Yellow input buttons now use official SAP color
Cards now have a selectable and non selectable state available via classes

RELEASE/v0.2.4: release

---

src/less/components/_spinner.less
src/less/styles.less

just commited and pushed two files.

Spinner added to a fresh feature branch.

---

src/less/overwrites/_buttons.less

Creating a new PR because the old did not give any option to change the base branch.

Removed outline from button active, focus, default state.

---

docs/markdown/Guidelines.md
docu/release_notes/2015-12-04-Techne101.html

changed hyperlink to section-14

Cce 330 hyperlink

---

docs/template/index.html
src/less/components/_products.less
src/less/components/_table.less
src/less/components/_tree.less
src/less/overwrites/_labels.less
src/less/overwrites/_popover.less
src/less/overwrites/_tabs.less
src/less/styles.less

Removed product thumbnail and changed hyperlinks on components page.

CCE-329 remove product thumbnail

---

package.json

Possibility installing via npm

transfer devDependencies to dependencies

---

src/less/components/_forms-help.less

Section Inline Level help for read-only fields

Inline help right after the input

---

src/less/techne-patterns/_data-card.less
src/less/techne-patterns/_expandable-button.less
src/less/techne-patterns/_tables.less
src/less/techne-patterns/_toolbar.less

@saadmhybris 
Please test this, specially on cards and toolbar. The autoprefixer is on and working, but if something is wrong things will break

CCE-546: removed vendor prefixed css, except the very specific ones

---

package.json

After some quick debugging, looks like we need lodash so adding it back in this PR so that we are not blocked from working on other tickets. We may need a separate ticket to look at lodash and whether or not to include it in the future.

CCE-668: adding back lodash.

---

package.json
src/less/components/_forms-checkboxes.less

Ticket - https://jira.hybris.com/browse/CCE-615

CCE-615 : checkbox icon update and alignment fix

---

ops/README.md
ops/gulp/build.js
ops/gulp/clean.js
ops/gulp/docs-clean.js
ops/gulp/pkg-clean.js

Revert "#681: Global Build and Clean gulp commands added. Docs clean refactor…"

---

docs/styleguide/styles.html
docs/styleguide/styles/_code.scss
src/styles/all.scss
src/styles/components/button.scss
src/styles/components/card.scss
src/styles/core/_mixins.scss
src/styles/core/_settings.scss
src/styles/helpers.scss
src/styles/helpers/_general.scss
src/styles/helpers/_type.scss

Specs have been added to the Styles page at http://localhost:3000/styles.html

#729 updates font sizes, enhances mixin, sets helper classes

---

src/less/components/_forms-validationandhelp.less

Enforce use of techne help bubble.

CCE-695 Correct help bubble

---

docs/styleguide/components/cards.html
docs/styleguide/components/layout-test.html
docs/styleguide/includes/type.html
ops/gulp/dev-watch.js
src/styles/components/button.scss
src/styles/components/card.scss
src/styles/components/table.scss
src/styles/core/_settings.scss
src/styles/helpers/_type.scss

See #798. Fixes regression bugs related to new color specs.

#798 updates Cards colors based on new specs

---

ops/gulp/docs-html.js

#834 handles nunjucks errors

---

src/styles/components/card.scss
src/styles/core/_functions.scss
src/styles/core/_mixins.scss
src/styles/core/_settings.scss
src/styles/core/elements.scss
src/styles/helpers/_type.scss

#714 namespaces all variables

---

src/styles/layout/container.scss

#847 fixes broken var

---

test/README.md

#877 
Small update. Adds instructions to help designers set up the project for visual testing.

#877 updates test/README with details for visual testing

---

scss/components/form.scss

#922 adds bottom margin back to inline labels

---

ops/gulp/create.js
scss/components.scss
scss/components/badge.scss
scss/components/label.scss
test/templates/badge/component.njk
test/templates/badge/data.json
test/templates/badge/index.njk
test/templates/index.njk
test/templates/label/component.njk
test/templates/label/data.json
test/templates/label/index.njk

#914
See branch `feature/914`. Two pages http://localhost:3030/label and http://localhost:3030/badge

#914 labels and badges

---

docs/_data/sidebars/components-sidebar.yml

#945 
- remove action bar 
- removed layout 
- removed list 
- removed label 
- added status indicator

#945: Docs - Remove incomplete components

---

docs/_data/sidebars/components-sidebar.yml
docs/pages/components/status-indicators.md

#939 
- added status indicator components page.

#939: Docs - Implement status indicators

---

scss/components.scss
scss/components/alert.scss
test/templates/alert/component.njk
test/templates/alert/data.json
test/templates/alert/index.njk
test/templates/index.njk
test/templates/layout.njk

#855: Pkg - Alerts

---

scss/components/contextual-menu.scss
scss/components/dropdown.scss
test/app.js
test/templates/contextual-menu/data.json
test/templates/contextual-menu/index.njk
test/templates/dropdown/component.njk
test/templates/dropdown/index.njk
test/templates/index.njk

#916 contextual menu

---

ops/gulp/dev-jekyll.js

#966 
This will fix gem version errors.

#966: update jekyll build task to prepend bundle exec 

---

docs/pages/components/card.md

#989: update contextual menu on action card.

---

docs/_data/sidebars/components-sidebar.yml
docs/css/customstyles.css
docs/pages/components/pagination.md

#987: Docs - Pagination

---

docs/_data/sidebars/components-sidebar.yml
docs/pages/components/card-group.md

#1000: Docs - Card Group

---

test/templates/layout.njk

#1027 changes background color of test page

---

test/app.js
test/templates/contextual-menu/index.njk

#1029 fixes icons font route

---

docs/_data/sidebars/components-sidebar.yml
docs/css/customstyles.css
docs/pages/components/table.md
test/templates/table/component.njk

Docs - Implement table component

---

test/templates/index.njk
test/templates/pages/index.njk
test/templates/pages/table.njk

#1004: Pkg - Implement Table starter page

---

scss/components/input-group.scss

#938 
Not sure if this is the best way to fix this, but this PR review will answer my questions I guess :)

#938: fix alignment problems with spinner buttons

---

docs/pages/components/action-bar.md
docs/starter-pages/index.md

#1048 Added uses cases and documentation

---

scss/components/dropdown.scss
scss/components/input-group.scss
scss/components/modal.scss

#1016: remove core/forms.scss from components to avoid duplication.

---

scss/components/input-group.scss
test/templates/input-group/index.njk

#1103 changes default to full width; adds inline option

---

docs/pages/components/tree.md

#1127 Remove icons fixed on tree

---

scss/components/card-group.scss
scss/components/dropdown.scss
scss/components/form.scss
scss/components/table.scss
scss/components/toolbar.scss
scss/components/tree.scss
scss/core/forms.scss
scss/layout/section.scss
test/templates/pages/cards.njk
test/templates/pages/layouts/module.njk
test/templates/pages/module.njk
test/templates/pages/table.njk
test/templates/pages/tree.njk
test/templates/toolbar/component.njk

#1168 
Updates all three starter pages (card, tree, and table) to use new layout containers. Also, includes a few small tweaks of various margins.

#1168 updates starter pages with new layout containers

---

scss/components.scss
scss/components/tabs.scss
test/templates/index.njk
test/templates/nav/component.njk
test/templates/nav/index.njk
test/templates/tabs/component.njk
test/templates/tabs/data.json
test/templates/tabs/index.njk
test/templates/utils.njk

#1011 implements tabs

---

docs/_data/sidebars/components-sidebar.yml
docs/js/customscripts.js
docs/pages/components/tabs.md
scss/components.scss

#1201 added tabs component page

---

docs/_data/sidebars/left-navigation-sidebar.yml
docs/pages/components/panel.md

#1199: Docs - panels

---

scss/components/tree.scss

#1123 adds hover transition to tree row

---

.npmignore

#1276 adds theme dir to npm package

---

scss/components/list-group.scss

#1289: zero out left margin on list component

---

scss/components/card.scss

#1098 forces no decoration on button card

---

docs/pages/fundamentals/type.html

#1308 : copy update on type page

---

docs/pages/fundamentals/grid.html

#1306 copy updates on grid page
